Добавлен CI файл
gpb-it-factory/morkovnikov-telegram-bot pull request #6
Opened 2024-05-18 20:46 UTC by RojoBlanco

Добавлен yml файл, который будет билдить и тестить приложение при открытии, переоткрытии Pull request и добавлении комита в него

2024-05-20 09:42 UTC, konstantin-kozlovskiy requested changes
Надо поправить моменты из комментариев

2024-05-20 09:42 UTC, konstantin-kozlovskiy commented on .github/workflows/telegrambot-ci.yml
> +        run: ./gradlew build
build таска и так вызывает test, получается test вызывается 2 раза

2024-05-20 09:42 UTC, konstantin-kozlovskiy commented on .github/workflows/telegrambot-ci.yml
> +          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
зачем для тестов передавать токен? да и для билда он тоже не нужен

2024-05-20 09:42 UTC, konstantin-kozlovskiy commented on .github/workflows/telegrambot-ci.yml
> +        run: ./gradlew build
./gradlew build -x test

2024-05-20 10:19 UTC, RojoBlaco commented on .github/workflows/telegrambot-ci.yml
> +        run: ./gradlew build
Согласен, поправил!

2024-05-20 10:25 UTC, RojoBlaco commented on .github/workflows/telegrambot-ci.yml
> +          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
У меня почему то не проходят тесты без токена, с помощью команды  run: ./gradlew test --scan --info я вызвал логи, и нашел там такую ошибку. 
![brave_CxX0jtDUtM](https://github.com/gpb-it-factory/morkovnikov-telegram-bot/assets/116725781/f6263f0e-0cfe-40fa-89e5-678aa33c5f56)

Не понял с чем это связано, на моей машине все тесы проходят даже если я удалю token: ${TELEGRAM_TOKEN} из application.yml, но здесь почему то ругается

2024-05-23 05:27 UTC, konstantin-kozlovskiy approved these changes

2024-05-23 06:58 UTC, merged