Добавил отправку id пользователя на Middle - сервис и обработку ответа
gpb-it-factory/morkovnikov-telegram-bot pull request #9
Opened 2024-05-25 22:15 UTC by RojoBlanco

2024-05-31 12:48 UTC, RojoBlanco commented
Решил после вчерашней лекции попробовать написать тесты)

2024-06-03 05:41 UTC, vaganov-vadim requested changes
Привет! Изменения сами по себе хорошие, а тесты - это вообще отлично, ты молодец! Добавил советов и обратной связи по возможным улучшениям.

2024-06-03 05:41 UTC, vaganov-vadim commented on src/main/kotlin/ru/gpb/telegrambot/commands/RegisterCommand.kt
> +    private val responseTemplate: RestTemplate,
В целом, спрингом рекомендуется не использовать RestTemplate. Либо использовать WebClient, либо новый RestClient (по-моему появился в 3+).

2024-06-03 05:41 UTC, vaganov-vadim commented on src/main/kotlin/ru/gpb/telegrambot/commands/RegisterCommand.kt
> +    private val responseTemplate: RestTemplate,
Мне кажется, что в данном случае чуть логичнее прокидывать абстракцию, а не url и веб-клиент. Так проще тестировать и подстраиваться под новые вводные.

2024-06-03 05:41 UTC, vaganov-vadim commented on src/main/kotlin/ru/gpb/telegrambot/commands/RegisterCommand.kt
> +        val registerEndpoint = "${url}/register"
Опять же, детали "общения" лучше скрыть в самом клиенте/абстракции (а лучше вообще из конфига это брать). Это не команда должна знать, куда стучаться, а клиент.

2024-06-03 05:41 UTC, vaganov-vadim commented on src/main/kotlin/ru/gpb/telegrambot/enums/CommandEnum.kt
>  enum class CommandEnum(val command: String, val description: String) {
Выглядит так, что этот enum в принципе не нужен. У тебя эти данные ведь используются только в самих командах? Может, эти данные и инкапсулировать в самих командах?

2024-06-03 05:41 UTC, vaganov-vadim commented on src/test/kotlin/ru/gpb/telegrambot/commands/RegisterCommandTest.kt
> +    private val restTemplate = Mockito.mock(RestTemplate::class.java)
Вот тут как раз и сыграла бы та самая абстракция, мокать было бы удобнее. Можно даже без Mockito обойтись и просто создать свою простую заглушку.

2024-06-03 05:41 UTC, vaganov-vadim commented on src/test/kotlin/ru/gpb/telegrambot/commands/RegisterCommandTest.kt
> +    @Test
В JUnit классно использовать аннотацию @DisplayName - там можно писать по-русски и именно содержимое этой аннотации будет выводиться при запуске тестов.

2024-06-03 05:41 UTC, vaganov-vadim commented on src/test/kotlin/ru/gpb/telegrambot/commands/RegisterCommandTest.kt
> +        val argumentCaptor = ArgumentCaptor.forClass(SendMessage::class.java)
Вот такие штуки иногда говорят о том, что наш тест слишком много знает о внутренном устройстве кода. Лучше тестировать сугубо на уровне контрактов - при таком-то вводе такой-то вывод. Но если есть сайд-эффект, то без шпионов/моков обойтись трудно.
Но по моему мнению - нам тут не нужно проверять исполняемые шаги, только получаемый результат.

2024-06-03 05:41 UTC, vaganov-vadim commented on src/test/kotlin/ru/gpb/telegrambot/commands/RegisterCommandTest.kt
> +        val argumentCaptor = ArgumentCaptor.forClass(SendMessage::class.java)
Аналогично как и выше, такие вещи очень неустойчивы к рефакторингу.

2024-06-04 14:26 UTC, RojoBlanco commented on src/main/kotlin/ru/gpb/telegrambot/commands/RegisterCommand.kt
> +    private val responseTemplate: RestTemplate,
Не знал что не рекомендуется, выбирал потому что уже работал с RestTemplate) Почитал, решил выбрать RestClient, потому что как пишут  WebClient используется с реактивностью, а туда лезть я пока не готов, с этим бы добром разобраться)

2024-06-04 14:29 UTC, RojoBlanco commented on src/main/kotlin/ru/gpb/telegrambot/commands/RegisterCommand.kt
> +    private val responseTemplate: RestTemplate,
Добавил клиента посылающего запросы, тестировать действительно стало проще, кода меньше и понятно что тестировать

2024-06-04 14:31 UTC, RojoBlanco commented on src/main/kotlin/ru/gpb/telegrambot/commands/RegisterCommand.kt
> +        val registerEndpoint = "${url}/register"
Тут немного не понял, я сделал конфиг RestClienta, но там задал только url, на который стучаться, а эндпоинт добавляю уже в клиенте, при отправке запроса. Правильно ли это? Или все эндпоинты так же в конфиге создавать?  (Что звучит странно, зачем нам плодить миллион бинов на каждый эндпоинт отдельно)

2024-06-04 14:32 UTC, RojoBlanco commented on src/main/kotlin/ru/gpb/telegrambot/enums/CommandEnum.kt
>  enum class CommandEnum(val command: String, val description: String) {
Убрал enum

2024-06-04 14:34 UTC, RojoBlanco commented on src/test/kotlin/ru/gpb/telegrambot/commands/RegisterCommandTest.kt
> +    private val restTemplate = Mockito.mock(RestTemplate::class.java)
Да, действительно, кода стало в разы меньше. Я правда не понял как создать свою заглушку, у меня в голове только создать сервер тестовый, на который слать запрос, но это не решает проблемы, все равно для тестов его придется поднимать. Можешь показать пример пожалуйста?

2024-06-04 14:35 UTC, RojoBlanco commented on src/test/kotlin/ru/gpb/telegrambot/commands/RegisterCommandTest.kt
> +    @Test
Добавил, дейстивительно стало удобнее смотреть какие тесты пройдены, а какие нет

2024-06-04 14:38 UTC, RojoBlaco commented on src/test/kotlin/ru/gpb/telegrambot/commands/RegisterCommandTest.kt
> +        val argumentCaptor = ArgumentCaptor.forClass(SendMessage::class.java)
Согласен, но сейчас не понимаю как здесь обойтись без моков когда тестирую отправку запроса не сервис. Входные данные всегда одни, и результат зависит больше от других сервисов

2024-06-04 14:41 UTC, RojoBlanco commented
Так же решил удалить StartCommandTest, потому что он ничего не проверяет особо, там всегда один ответ. Понял это благодаря добавлению клиента, действительно при вынесении такой абстракции становиться понятно что нужно тестировать)

2024-06-11 05:20 UTC, vaganov-vadim commented on src/test/kotlin/ru/gpb/telegrambot/commands/RegisterCommandTest.kt
> +    private val restTemplate = Mockito.mock(RestTemplate::class.java)
Я имел в виду просто реализацию интерфейса, которая что-то возвращает в ответ. В юнит-тестах тебе необязательно взаимодействовать с внешним миром.

2024-06-11 05:30 UTC, vaganov-vadim requested changes
Отличная работа, стало прям в сто раз лучше! Добавил ещё коммент по поводу выноса клиента миддл-сервиса в интерфейс, тогда мы вообще можем избавиться от всех тяжеловесных моков - тесты будут просто очень читаемые, плюс мы отвяжемся от реализации взаимодействия, у нас будет только контракт. Если будут вопросы - пиши.

2024-06-11 05:30 UTC, vaganov-vadim commented on src/main/kotlin/ru/gpb/telegrambot/client/MiddleServiceClient.kt
> +class MiddleServiceClient(
Здорово! Единственное - здесь видится вынос интерфейса со следующим соображением: API может уехать куда угодно (HTTP, Kafka, ещё куда), и это по большому счёту внешная зависимость, такие как раз очень разумно привязывать к своей логике только на уровне контракта.

2024-06-11 05:30 UTC, vaganov-vadim commented on src/test/kotlin/ru/gpb/telegrambot/commands/RegisterCommandTest.kt
> +    private val middleServiceClient = MiddleServiceClient(restClient)
Если сделать интерфейс для клиента, то и мокать рест-клиент не придётся :)

2024-06-11 05:30 UTC, vaganov-vadim commented on src/test/kotlin/ru/gpb/telegrambot/commands/RegisterCommandTest.kt
> +        val argumentCaptor = ArgumentCaptor.forClass(SendMessage::class.java)
Смотри в другом комменте :)

2024-06-11 05:31 UTC, vaganov-vadim commented
А, да, переименуй сам PR, пожалуйста, он назван не по соглашению.

2024-06-22 11:01 UTC, vaganov-vadim commented on src/main/kotlin/ru/gpb/telegrambot/commands/RegisterCommand.kt
> +            val response= middleServiceClient.registerUser(user.id, user.userName)
С форматированием где-то слегка проблемки, прогони потом форматтером.

2024-06-22 11:03 UTC, vaganov-vadim commented on src/test/kotlin/ru/gpb/telegrambot/commands/RegisterCommandTest.kt
> +        val result = middleServiceClient.registerUser(telegramUserId, userName)
Не уверен, что это очень полезный тест. Может, проверить от уровня повыше? А то мы тут проверяем, что наш стаб работает так, как задумано, что странновато.

2024-06-22 11:03 UTC, vaganov-vadim requested changes
По всем правкам ок, но давай по тесту подумаем, сейчас в нём мало смысла.

2024-06-29 09:53 UTC, vaganov-vadim submitted a review, later dismissed
Пара комментов актуальны, в личке обсудили. В остальном ревью не блочу. Аппрув!

2024-07-03 15:35 UTC, vaganov-vadim approved these changes

2024-07-03 15:35 UTC, merged